### ISSUE TITLE
tests fail on go1.5 (pass on go1.4.2) darwin/amd64

### ISSUE THREAD

**Issue by elliott5** [nelhage/gojit#8]
```
Elliotts-MacBook-Pro15:gojit elliott$ go test
unexpected fault address 0x1000
fatal error: fault
[signal 0xb code=0x1 addr=0x1000 pc=0x1000]

goroutine 20 [running]:
runtime.throw(0x4187c48, 0x5)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc82003ce38 sp=0xc82003ce20
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc82003ce88 sp=0xc82003ce38
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x41cd6e8, 0x4245180, 0x2, 0x2, 0x1)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820051ef8, 0xc820076550)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/nelhage/gojit/_test/_testmain.go:60 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
FAIL	github.com/nelhage/gojit	0.011s
```

**Comment by thinxer** [comment]
Failing here too with Go 1.5.1, on linux/amd64.

**Comment by cespare** [comment]
I don't know if this is the only problem, but I noticed that this code is out of date for the new interface representation:

https://github.com/nelhage/gojit/blob/master/jit.go#L106-L110

Interfaces now always contain pointers, even for data that fits into a word.
